### ISSUE TITLE
Slider plugin

### ISSUE THREAD

**Issue by averyhadzi** [trinary/mention-network#1]
Hey Erik!

Upon looking further into the dat.GUI controls, it doesn't seem like I'll be able to style it to match the mockups. :(

I hate to be a pain, but is there a way to implement a different library? Something like this would be ideal: http://abpetkov.github.io/powerange/, or at the very least, something like the jQuery UI slider (though it would probably be a lot heavier). 

If we're in too deep with the dat.GUI sliders, I can talk to the team about adjusting the style guide to accommodate, but using something more customizable would be ideal.

Please let me know!

Thank you!

**Comment by trinary** [comment]
Sure, we aren't too tied to Dat, it's just my go-to for easy controls. All I need is a callback to trigger websocket message-passing between vis and control.
